{
  parserClass="com.maddyhome.idea.copyright.language.parser.SimpleParser"
  parserUtilClass="com.maddyhome.idea.copyright.language.parser.SimpleParserUtil"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="com.maddyhome.idea.copyright.language.psi"
  psiImplPackage="com.maddyhome.idea.copyright.language.psi.impl"

  elementTypeHolderClass="com.maddyhome.idea.copyright.language.psi.SimpleTypes"
  elementTypeClass="com.maddyhome.idea.copyright.language.psi.SimpleElementType"
  tokenTypeClass="com.maddyhome.idea.copyright.language.psi.SimpleTokenType"

  extends(".*Expr")=expr

}

simpleFile ::= item_*

statement ::= (ALIAS | AS | CASE | ELSE | EXPOSING | IF | IN | LET | MODULE | OF | OTHERWISE | PORT | THEN | TYPE )

operator ::= (LBRACE | RBRACE | LBRACK | RBRACK | COLON | EQ | ASSIGN | NOT_EQ | NOT | PLUS | MINUS | COND_OR | COND_AND
  | BIT_AND | SEND_CHANNEL | LESS | BIT_XOR | MUL | QUOTIENT | REMAINDER | GREATER
  | TILDE | PIPE_FORWARD | BACK_TICK | COMBINE | MULTIMAP | PIPE_BACK | GE | LE | COMBINE_BACK
  | COLON_COLON | INT_DIVIDE | DOT_DOT | DOT | RETURN | BIT_OR )

private item_ ::=
  import_statement
  | module_statement
  | fun_decl
  | fun_def
  | COMMENT
  | MULTILINE_COMMENT
  | type_alias
  | type_decl
  | let_statement
  | port_def
  | port_decl


module_statement ::= MODULE module_body WHERE
module_body ::= compound_identifier L_PAREN exposing_list R_PAREN

import_statement ::= IMPORT import_body
import_body ::= compound_identifier EXPOSING L_PAREN exposing_list R_PAREN
exposing_list ::= IDENTIFIER [(COMMA IDENTIFIER)*] | DOT_DOT

fun_decl ::= IDENTIFIER COLON [type_param (RETURN type_param)*]
type_param ::= TYPE_IDENTIFIER
  | L_PAREN TYPE_IDENTIFIER [(COMMA TYPE_IDENTIFIER)*] R_PAREN
fun_def ::= IDENTIFIER [params] ASSIGN fun_body
params ::= param*
param ::= (IDENTIFIER | tuple | record | list_type) [AS IDENTIFIER]
fun_body ::= expr | let_statement

port_decl ::= PORT IDENTIFIER COLON (compound_identifier)*
port_def ::= PORT IDENTIFIER ASSIGN (compound_identifier)*

type_decl ::= TYPE IDENTIFIER ASSIGN type_body
type_body ::= type_body_part [ BIT_OR type_body_part ]
type_body_part ::= tag [compound_identifier]
tag ::= IDENTIFIER

type_alias ::= TYPE ALIAS type_alias_body
type_alias_body ::= compound_identifier ASSIGN (compound_identifier | tuple | record | list_type)

let_statement ::= LET let_body IN expr
let_body ::=  [fun_decl] fun_def | (let_body_part)+
let_body_part ::= IDENTIFIER ASSIGN expr

compound_identifier ::= IDENTIFIER [(DOT IDENTIFIER)*]
tuple ::= LPAREN expr [ (COMMA expr)*] R_PAREN
record ::= LBRACE expr [ (COMMA expr)*] RBRACE
list_type ::= LIST [compound_identifier]


expr ::=
  NumberExpr
  | StringExpr
  | OrExpr
  | AndExpr
  | ConditionalExpr
  | AddExpr
  | MulExpr
  | UnaryExpr
  | IdExpr
  | TupleExpr
  | RecordExpr
  | RecordUpdateExpr
  | ListExpr
  | IfExpr
  | CaseExpr
  | ParenthesesExpr


OrExpr ::= expr COND_OR expr
AndExpr ::= expr COND_AND expr
UnaryExpr ::=  unary_op expr
ConditionalExpr ::= expr rel_op expr
AddExpr ::= expr add_op expr
MulExpr ::= expr mul_op expr
TupleExpr ::= tuple
RecordExpr ::= record
ListExpr ::= list
NumberExpr ::= NUM
StringExpr ::= STR
IdExpr ::= compound_identifier
IfExpr ::= IF expr THEN expr [ELSE expr]
CaseExpr ::= case_statement
ParenthesesExpr ::= L_PAREN expr R_PAREN
RecordUpdateExpr ::= LBRACE record_name BIT_OR record_update_body RBRACE

record_name ::= IDENTIFIER
record_update_body ::= record_update_body_part [(record_update_body_part)*]
record_update_body_part ::= field_name SEND_CHANNEL expr
field_name ::= IDENTIFIER

case_statement ::= CASE IDENTIFIER OF case_body
case_body ::= (case_body_part)* [OTHERWISE expr]
case_body_part ::= expr RETURN expr


private rel_op ::= EQ | NOT_EQ | LESS | LE | GREATER | GE
private add_op ::= PLUS | MINUS
private mul_op ::= MUL | QUOTIENT | INT_DIVIDE | REMAINDER
private unary_op ::= PLUS | MINUS | NOT

/*
  1) Add single apostrophe to identifier chars - cannot be first char - single quotes not supported for string
  * 2) {recname | id <- expr, id <- xpr } SEND_CHANNEL
  3) detect type identifiers by Capital case
  4) concat relationship with COLON_COLON operator
 */