<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output encoding="utf-8" method="html" indent="yes" xml:space="default"/>

    <!-- requires a directory tree generated by dir-2-xml with a single root node -->


    <xsl:template match="/directory">
        <ul class="tree">
            <li><xsl:value-of select="@name"/>
            <ul><xsl:apply-templates/></ul>
            </li>
        </ul>
    </xsl:template>

    <xsl:template match="directory">
        <li><xsl:value-of select="@name"/>
        <ul>
            <xsl:apply-templates/>
        </ul>
        </li>
    </xsl:template>
    <xsl:template match="file">
            <li><xsl:value-of select="@name"/></li>
    </xsl:template>
    <xsl:template match="directory[@name='target']">
        <li class='target'><xsl:value-of select="@name"/>
        <ul>
            <xsl:apply-templates/>
        </ul>
        </li>
    </xsl:template>
    <xsl:template match="directory[@name='.idea']">
    </xsl:template>
    <xsl:template match="file[@name='quickstart.pom']">
    </xsl:template>

</xsl:stylesheet>