using Microsoft.EntityFrameworkCore.Migrations;

/*
    Constraints & Dependencies:
    a) Save <dbcontext>ModelSnapshot to support Database.Migrate()
    b) Git-ignore model based migrations so as not to confuse other devs.
    c) Database is disposable - completely reconstructable
    d) Model migrations should not have dependencies on custom migrations.

    migrations workflow (to include custom sql).
    
    From scratch:
    1. drop all objects from database
    2. remove any migrations generated from model that happen to be hanging about
    3. remove <dbConext>ModelSnapshot (starting point for migrations generated from mdeol)
    4. execute "dotnet ef migrations add start" - to generate migrations from model
    5. execute "dotnet ef migrations add custom" - to generate an empty migration
    6. Populate Up() and Down() body of class generated by custom (not the Designer)
       calls static methods from the CustomSql directory.
    7. execute "dotnet ef database update"
     
    Incremental:
    1. Add a static class containing the Up() and Down() in CustomSql. 
    2. execute "dotnet ef migrations add <something>" - to generate migrations from model
    3. execute "dotnet ef migrations add custom-n" - to generate an empty migration
    4. Populate Up() and Down() body of class generated by custom (not the Designer)
       calls static methods from the CustomSql directory which have just been created.
    5. execute "dotnet ef database update"
    6. consolidate static custom methods in the CustomSql directory.
    
    It may not be possible to consolidate all custom sql scripts as the
    dependency graphs may not allow it. 
     
    create migrations from model and (optionally) update database
    
*/

namespace Nute.Migrations.CustomSql
{
    public static partial class NutritionProfileView
    {
        internal static void Up(MigrationBuilder mib)
        {
            mib.Sql(upScript);
        }

        internal static void Down(MigrationBuilder mib)
        {
            mib.Sql("drop view NutrientProfile_v");
        }
    }
}
