// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nute;

namespace Nute.Migrations
{
    [DbContext(typeof(NutritionDbContext))]
    partial class NutritionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nute.Entities.BodyType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("BodyType");

                    b.HasData(
                        new { Id = 1L, Description = "Male Std.", Name = "Male" },
                        new { Id = 2L, Description = "Female Std.", Name = "Female" }
                    );
                });

            modelBuilder.Entity("Nute.Entities.Constituent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("IngredientId");

                    b.Property<long?>("NutrientId");

                    b.Property<decimal>("_quantityCount")
                        .HasColumnName("QuantityCount");

                    b.Property<long>("_quantityUnitId")
                        .HasColumnName("QuantityUnitId");

                    b.Property<decimal>("_servingSizeCount")
                        .HasColumnName("servingSizeCount");

                    b.Property<long>("_servingSizeUnitId")
                        .HasColumnName("ServingSizeUnitId");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("NutrientId");

                    b.HasIndex("_quantityUnitId");

                    b.HasIndex("_servingSizeUnitId");

                    b.ToTable("Constituent");
                });

            modelBuilder.Entity("Nute.Entities.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<decimal>("_servingSizeCount")
                        .HasColumnName("servingSizeCount");

                    b.Property<long>("_servingSizeUnitId")
                        .HasColumnName("ServingSizeUnitId");

                    b.HasKey("Id");

                    b.HasIndex("_servingSizeUnitId");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("Nute.Entities.Nutrient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("Subsidiary")
                        .HasAnnotation("comment", "subsidiary nutrients (e.g. saturated fats) would not be included in any calculation of an ingredients weight - if we actually did that");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name")
                        .HasName("AK_Nutrient_Name");

                    b.ToTable("Nutrient");

                    b.HasData(
                        new { Id = 1L, Name = "Energy", Subsidiary = false },
                        new { Id = 2L, Name = "Fat", Subsidiary = false },
                        new { Id = 3L, Name = "Saturated Fat", Subsidiary = false },
                        new { Id = 4L, Name = "Carbohydrate", Subsidiary = false },
                        new { Id = 5L, Name = "Sugars", Subsidiary = false },
                        new { Id = 6L, Name = "Fibre", Subsidiary = false },
                        new { Id = 7L, Name = "Protein", Subsidiary = false },
                        new { Id = 8L, Name = "Salt", Subsidiary = false }
                    );
                });

            modelBuilder.Entity("Nute.Entities.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbrev")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Abbrev")
                        .HasName("AK_Unit_Abbrev");


                    b.HasAlternateKey("Name")
                        .HasName("AK_Unit_Name");

                    b.ToTable("Unit");

                    b.HasData(
                        new { Id = 1L, Abbrev = "g", Name = "gram" },
                        new { Id = 2L, Abbrev = "ea", Name = "each" },
                        new { Id = 3L, Abbrev = "lge", Name = "large" },
                        new { Id = 4L, Abbrev = "kcal", Name = "calorie" },
                        new { Id = 5L, Abbrev = "mg", Name = "milligram" },
                        new { Id = 6L, Abbrev = "μg", Name = "micro-gram" }
                    );
                });

            modelBuilder.Entity("Nute.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasAlternateKey("Token");

                    b.ToTable("User");

                    b.HasData(
                        new { Id = 1L, Token = "magic1" }
                    );
                });

            modelBuilder.Entity("Nute.Entities.Version", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("SequenceNumber");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Version");

                    b.HasData(
                        new { Id = 1L, SequenceNumber = 1, StartDate = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Local) }
                    );
                });

            modelBuilder.Entity("Nute.Entities.Constituent", b =>
                {
                    b.HasOne("Nute.Entities.Ingredient")
                        .WithMany("Constituents")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nute.Entities.Nutrient", "Nutrient")
                        .WithMany()
                        .HasForeignKey("NutrientId");

                    b.HasOne("Nute.Entities.Unit", "_quantityUnit")
                        .WithMany()
                        .HasForeignKey("_quantityUnitId");

                    b.HasOne("Nute.Entities.Unit", "_servingSizeUnit")
                        .WithMany()
                        .HasForeignKey("_servingSizeUnitId");
                });

            modelBuilder.Entity("Nute.Entities.Ingredient", b =>
                {
                    b.HasOne("Nute.Entities.Unit", "_servingSizeUnit")
                        .WithMany()
                        .HasForeignKey("_servingSizeUnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
